/*
  fielder artwork: 24 frames cut from the approved
  character sheet.

  GENERATED by scripts/install-sprites.mjs. Edit the name map in that script
  rather than this file — the numbers below are measured from the PNGs and
  will be overwritten on the next run.

  Two numbers per frame matter for placement:

  - `h` is measured against IDLEHIPS_H below. Frames are NOT normalised
    to a common height: a raised arm makes a frame taller without making the
    player taller, so scaling each to fit would shrink the body exactly when
    the action is biggest. Every frame uses the one scale derived from the
    reference pose, and limbs are free to leave the top.
  - `ax` is where the feet sit horizontally, as a fraction of frame width.
    An outstretched dive stretches the bounding box, so centring the box
    would slide the body across the ground between frames. Anchoring on the
    feet keeps the player planted. Measured from the alpha channel of the
    bottom 7% of each frame.
*/

export type FielderPose =
  | "idleHips"
  | "idleArms"
  | "idleHands"
  | "idleCrouch"
  | "idleCap"
  | "idleBack"
  | "sprint"
  | "sprintTurn"
  | "gather"
  | "chase"
  | "dive"
  | "slide"
  | "catchReady"
  | "catchHigh"
  | "catchLeap"
  | "catchLow"
  | "catchKnee"
  | "caught"
  | "celebrate"
  | "point"
  | "diveStop"
  | "appeal"
  | "missed"
  | "dejected";

import { kitFrame, kitReady, preloadKit, type TeamKit } from "./spriteKit";

type FrameMeta = { w: number; h: number; ax: number };

/** the reference pose's pixel height — the scale every frame is drawn at */
export const IDLE_HIPS_H = 264;

export const FIELDER_FRAMES: Record<FielderPose, FrameMeta> = {
  idleHips:   { w: 128, h: 264, ax: 0.5179 },
  idleArms:   { w: 143, h: 266, ax: 0.5311 },
  idleHands:  { w: 135, h: 263, ax: 0.4844 },
  idleCrouch: { w: 146, h: 208, ax: 0.4966 },
  idleCap:    { w: 125, h: 266, ax: 0.4269 },
  idleBack:   { w: 134, h: 265, ax: 0.4653 },
  sprint:     { w: 209, h: 193, ax: 0.5555 },
  sprintTurn: { w: 176, h: 200, ax: 0.6628 },
  gather:     { w: 178, h: 212, ax: 0.5443 },
  chase:      { w: 171, h: 198, ax: 0.6610 },
  dive:       { w: 271, h:  87, ax: 0.2740 },
  slide:      { w: 199, h: 123, ax: 0.4461 },
  catchReady: { w: 145, h: 190, ax: 0.5198 },
  catchHigh:  { w: 128, h: 252, ax: 0.5257 },
  catchLeap:  { w: 156, h: 250, ax: 0.9470 },
  catchLow:   { w: 203, h: 161, ax: 0.5808 },
  catchKnee:  { w: 152, h: 151, ax: 0.5397 },
  caught:     { w: 128, h: 239, ax: 0.4784 },
  celebrate:  { w: 136, h: 173, ax: 0.5145 },
  point:      { w: 135, h: 177, ax: 0.2588 },
  diveStop:   { w: 269, h:  85, ax: 0.1628 },
  appeal:     { w: 158, h: 181, ax: 0.4950 },
  missed:     { w: 142, h: 172, ax: 0.4749 },
  dejected:   { w: 151, h: 158, ax: 0.5232 },
};

export const FIELDER_POSES = Object.keys(FIELDER_FRAMES) as FielderPose[];

/** Kick off loading for one side. Safe to call repeatedly. */
export function preloadFielder(team: TeamKit) {
  preloadKit(team, "fielder", FIELDER_POSES);
}

/** A frame, or null while it is still loading — callers fall back to the
    procedural figure so the field is never empty on the first ball. */
export function fielderFrame(team: TeamKit, pose: FielderPose) {
  return kitFrame(team, "fielder", pose, FIELDER_FRAMES[pose]);
}

export function fielderReady(team: TeamKit) {
  return kitReady(team, "fielder", FIELDER_POSES);
}
