/*
  keeper artwork: 29 frames cut from the approved
  character sheet.

  GENERATED by scripts/install-sprites.mjs. Edit the name map in that script
  rather than this file — the numbers below are measured from the PNGs and
  will be overwritten on the next run.

  Two numbers per frame matter for placement:

  - `h` is measured against IDLE_H below. Frames are NOT normalised
    to a common height: a raised arm makes a frame taller without making the
    player taller, so scaling each to fit would shrink the body exactly when
    the action is biggest. Every frame uses the one scale derived from the
    reference pose, and limbs are free to leave the top.
  - `ax` is where the feet sit horizontally, as a fraction of frame width.
    An outstretched dive stretches the bounding box, so centring the box
    would slide the body across the ground between frames. Anchoring on the
    feet keeps the player planted. Measured from the alpha channel of the
    bottom 7% of each frame.
*/

export type KeeperPose =
  | "standFront"
  | "standPortrait"
  | "standGloves"
  | "standBack"
  | "standBackPortrait"
  | "standBackGloves"
  | "idle"
  | "lookLeft"
  | "lookRight"
  | "adjustGloves"
  | "tapKnees"
  | "stretch"
  | "shakeHands"
  | "communicate"
  | "diveLeft"
  | "diveRight"
  | "catchHigh"
  | "catchStanding"
  | "catchLow"
  | "stanceWide"
  | "stanceNarrow"
  | "stanceUpClose"
  | "diveFull"
  | "getUp"
  | "behindStumps"
  | "catchSquat"
  | "stepLeft"
  | "stepRight"
  | "quickRecover";

import { kitFrame, kitReady, preloadKit, type TeamKit } from "./spriteKit";

type FrameMeta = { w: number; h: number; ax: number };

/** the reference pose's pixel height — the scale every frame is drawn at */
export const IDLE_H = 120;

export const KEEPER_FRAMES: Record<KeeperPose, FrameMeta> = {
  standFront:        { w: 125, h: 350, ax: 0.5110 },
  standPortrait:     { w: 131, h: 345, ax: 0.5099 },
  standGloves:       { w: 131, h: 351, ax: 0.5340 },
  standBack:         { w: 128, h: 344, ax: 0.5222 },
  standBackPortrait: { w: 123, h: 342, ax: 0.4931 },
  standBackGloves:   { w: 123, h: 343, ax: 0.5145 },
  idle:              { w:  88, h: 120, ax: 0.4773 },
  lookLeft:          { w:  95, h: 127, ax: 0.4832 },
  lookRight:         { w:  90, h: 127, ax: 0.4819 },
  adjustGloves:      { w:  82, h: 132, ax: 0.5053 },
  tapKnees:          { w:  84, h: 132, ax: 0.4849 },
  stretch:           { w:  66, h: 144, ax: 0.5114 },
  shakeHands:        { w:  86, h: 135, ax: 0.3828 },
  communicate:       { w:  93, h: 127, ax: 0.3954 },
  diveLeft:          { w: 204, h:  75, ax: 0.4911 },
  diveRight:         { w: 178, h:  76, ax: 0.4989 },
  catchHigh:         { w:  59, h: 103, ax: 0.5100 },
  catchStanding:     { w:  63, h:  95, ax: 0.4813 },
  catchLow:          { w:  71, h:  95, ax: 0.4900 },
  stanceWide:        { w:  97, h:  91, ax: 0.4975 },
  stanceNarrow:      { w:  68, h:  96, ax: 0.4884 },
  stanceUpClose:     { w:  71, h:  98, ax: 0.5082 },
  diveFull:          { w: 221, h:  74, ax: 0.0702 },
  getUp:             { w: 140, h:  94, ax: 0.5245 },
  behindStumps:      { w:  72, h:  96, ax: 0.4867 },
  catchSquat:        { w:  80, h:  97, ax: 0.4947 },
  stepLeft:          { w: 100, h: 102, ax: 0.4841 },
  stepRight:         { w: 104, h: 101, ax: 0.4781 },
  quickRecover:      { w:  79, h:  96, ax: 0.5068 },
};

export const KEEPER_POSES = Object.keys(KEEPER_FRAMES) as KeeperPose[];

/** Kick off loading for one side. Safe to call repeatedly. */
export function preloadKeeper(team: TeamKit) {
  preloadKit(team, "keeper", KEEPER_POSES);
}

/** A frame, or null while it is still loading — callers fall back to the
    procedural figure so the field is never empty on the first ball. */
export function keeperFrame(team: TeamKit, pose: KeeperPose) {
  return kitFrame(team, "keeper", pose, KEEPER_FRAMES[pose]);
}

export function keeperReady(team: TeamKit) {
  return kitReady(team, "keeper", KEEPER_POSES);
}
